<?php

require_once __DIR__ . '/../src/Controller.php';
require_once __DIR__ . '/../src/View.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-20 at 22:21:54.
 */
class ControllerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Controller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Controller(new Application());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Controller::setView
     * @covers Controller::getView
     */
    public function testSetGetView()
    {
        $view = new View();
        
        $this->object->setView($view);
        
        $v = $this->object->getView();
        
        $this->assertSame($view, $v);
    }

    /**
     * @covers Controller::init
     * @todo   Implement testInit().
     */
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Controller::setApplication
     * @covers Controller::getResource
     */
    public function testSetGetApplication()
    {
        $app = new Application();
        $this->object->setApplication($app);
        $a = $this->object->getApplication();
        
        $this->assertSame($app, $a);
    }

    /**
     * @covers Controller::setParams
     * @covers Controller::getParams
     */
    public function testSetGetParams()
    {
        $p = array("ciao");
        $this->object->setParams($p);
        
        $this->assertSame($p, $this->object->getParams());
    }
}
