<?php
require_once __DIR__ . '/../src/EventManager.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-21 at 08:13:08.
 */
class EventManagerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var EventManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EventManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers EventManager::subscribe
     */
    public function testSubscribe()
    {
        $this->object->subscribe('hook', function(){});
    }
    
    /**
     * @expectedException RuntimeException
     */
    public function testNotCallable()
    {
        $this->object->subscribe("hook", "hello-world");
    }

    /**
     * @covers EventManager::publish
     */
    public function testPublish()
    {
        $calls = 0;
        $this->object->subscribe("hook", function() use (&$calls) {
            ++$calls;
        });
        
        $this->object->publish('hook');
        
        $this->assertSame(1, $calls);
    }
    
    /**
     * @covers EventManager::publish
     */
    public function testCallEmptyListener()
    {
        $this->object->publish('hook');
    }

    /**
     * @covers EventManager::clear
     * @todo   Implement testClear().
     */
    public function testClear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
