<?php

require_once dirname(__FILE__) . '/../src/Route.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-20 at 21:30:57.
 */
class RouteTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Route
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Route;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @expectedException RuntimeException
     */
    public function testStrangeExplode()
    {
        $this->markTestSkipped("Check if is router test");
        $this->object->explode(array('controller' => 'ciao', 'action' => 'hello'));
    }

    public function testAddParam()
    {
        $this->markTestSkipped("Check if is request test");
        $this->object->explode("/index/index");
        $this->object->addParams(array("hello" => "ciao"));
        $this->object->addParams(array("bella" => 'zi'));

        $p = $this->object->getParams();
        $this->assertEquals(2, count($p));
        $this->assertEquals("ciao", $p["hello"]);
        $this->assertEquals("zi", $p["bella"]);
    }

    public function testClearGetParams()
    {
        $this->markTestSkipped("Check if is router test");
        $uri = '/?hello=world';
        $this->object->explode($uri);
        $this->assertEquals("Index", $this->object->getControllerName());
        $this->assertEquals("index", $this->object->getActionName());
    }
}
